esphome:
  name: guition-screen-esp
  friendly_name: Guition Screen ESP

substitutions:
  home_page: lighting_1

packages:
  common: !include common.yaml
  device: !include devices/JC3248W535.yaml
  layout: !include layouts/480x320.yaml
